export { default as Footer } from './shared/Footer';
export { default as Hero } from './Hero';
export { default as Navbar } from './shared/Navbar';
export { default as Services } from './Services'
export { default as BookNow } from './shared/BookNow'
export { default as NewsletterBanner } from './shared/NewsletterBanner'
export { default as Workshops } from './Workshops'
export { default as ShopItemsCatalogue } from './ShopItemsCatalogue'
export { default as NewsPreview } from './NewsPreview'
export { default as Article } from './shared/Article'
